### ISSUE TITLE
Uppercase letter o and zero look quite alike

### ISSUE THREAD

**Issue by uzluisf** [abrudz/APL386#7]
I don't know if slashing the zero would go against the spirit of the original font but right now uppercase letter o and zero look quite alike which might cause some confusion.

![image](https://github.com/abrudz/APL386/assets/22332927/51a9f041-690d-4ba3-8dd3-5eef1967d71d)

**Comment by abrudz** [comment]
To keep `0` consistent with `⍬`, I've added a middle dot instead of a slash, so it can be reasoned that the dot is behind the tilde in `⍬`:
![comparison of ⍬, 0, o, O](https://github.com/abrudz/APL386/assets/10961427/e5c4a2ae-7475-42dd-a1f7-be26c50ebe64)
I hope this helps.
